Revert "Pin goreleaser to v0.181.1"
This reverts commit f3262b2. That was a temporary workaround for an
issue with goreleaser. I *think* that's resolved now, and hopefully this
change will resolve the new issue we're seeing in
https://github.com/buildpulse/test-reporter/runs/3965130267?check_suite_focus=true:

> Run goreleaser/goreleaser-action@v2
> Downloading https://github.com/goreleaser/goreleaser/releases/download/v0.181.1/goreleaser_Darwin_all.tar.gz
> Error: Unexpected HTTP response: 404